# Generated by Django 3.0.5 on 2020-08-02 07:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cse_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('notification', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=36)),
                ('clg_code', models.IntegerField()),
                ('uni_name', models.CharField(max_length=36)),
                ('semester', models.CharField(max_length=36)),
                ('coursename', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=36)),
                ('f_name', models.CharField(max_length=36)),
                ('m_name', models.CharField(max_length=36)),
                ('rno', models.CharField(max_length=36)),
                ('dob', models.DateField()),
                ('jy', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=36)),
                ('clg_code', models.IntegerField()),
                ('uni_name', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=36)),
                ('f_name', models.CharField(max_length=36)),
                ('m_name', models.CharField(max_length=36)),
                ('rno', models.CharField(max_length=36)),
                ('dob', models.DateField()),
                ('jy', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adm',
            name='user_name',
        ),
        migrations.AddField(
            model_name='adm',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Teacher_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('Attendance', models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], max_length=2)),
                ('Sign_in', models.TimeField(default=datetime.datetime(2020, 8, 2, 13, 29, 6, 153230))),
                ('Sign_out', models.TimeField()),
                ('Teacher_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_name', models.CharField(choices=[('PUT', 'PUT'), ('UT1', 'unit Test 1'), ('UT2', 'unit Test 2')], max_length=3)),
                ('Marks', models.IntegerField()),
                ('Note', models.TextField(blank=True, max_length=200, null=True)),
                ('Roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stu')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cse_subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('Attendance', models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], max_length=2)),
                ('Note', models.TextField(max_length=200, null=True)),
                ('Roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stu')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cse_subject')),
            ],
        ),
    ]
