# Generated by Django 3.0.5 on 2020-08-02 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200802_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_attendance',
            name='Sign_in',
            field=models.TimeField(default=datetime.datetime(2020, 8, 2, 13, 29, 30, 587592)),
        ),
    ]
