# Generated by Django 3.0.5 on 2020-08-02 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200802_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cse_subject',
            new_name='cse_subjects',
        ),
        migrations.AlterField(
            model_name='teacher_attendance',
            name='Sign_in',
            field=models.TimeField(default=datetime.datetime(2020, 8, 2, 13, 32, 35, 933987)),
        ),
    ]
