# Generated by Django 3.0.5 on 2020-08-04 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200804_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_performance',
            name='Paper_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_attendance',
            name='Sign_in',
            field=models.TimeField(default=datetime.datetime(2020, 8, 4, 19, 56, 41, 336913)),
        ),
    ]
