# Generated by Django 3.0.5 on 2020-08-04 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200804_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher_attendance',
            name='Teacher_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher_attendance',
            name='Sign_in',
            field=models.TimeField(default=datetime.datetime(2020, 8, 4, 21, 19, 39, 1887)),
        ),
    ]
